### ISSUE TITLE
error during installing the environment

### ISSUE THREAD

**Issue by sonercandas** [tum-ens/pyPRIMA#58]
When I tried to install the environment with the command `conda env create -f gen_mod.yml`, I get the following error:
![image](https://user-images.githubusercontent.com/17904824/69228715-5baeea80-0b84-11ea-8675-8442087d860a.png)

And then when I want to run the script by `python runme.py`, the package `osgeo` cannot be found:
![image](https://user-images.githubusercontent.com/17904824/69228784-7f723080-0b84-11ea-8ca4-eea763695277.png)

**Comment by kais-siala** [comment]
osgeo was the first thing to be imported. You get the error because the environment has not been properly installed.
@HoussameH : we had this issue with some participants (not all), plus the Macintosh people (but that is expected). It has sth to do with the versions of the packages that we require, I suspect. Can we loosen up some of the requirements?

**Comment by sonercandas** [comment]
With my new anaconda version, it installs the environment properly.
